places = ['ausjg', 'mehsjk', 'engljd', 'nodse', 'csgds']
print(places)
print(sorted(places))
print(places)
print(sorted(places, reverse = True))
print(places)
places.reverse()
print(places)
print(places)
places.sort()
print(places)
print(places)
places.sort(reverse = True)
print(places)
print(places)
print(len(places))
